services:
  discordbot:
    image: discordbot
    build:
      context: .
      dockerfile: ./Dockerfile
    privileged: true
    volumes:
      # forward all usb devices
      - /dev/bus/usb:/dev/bus/usb
