services:
  discord-bot:
    build: .
    privileged: true
    devices:
      - /dev/bus/usb/001/003:/dev/bus/usb/001/003
    volumes:
      - /dev:/dev
      - /run/udev:/run/udev:ro
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped